[package]
name = "remoteops-domain"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
