[package]
name = "remoteops-device"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
base64.workspace = true
process-wrap.workspace = true
remoteops-domain = { path = "../remoteops-domain" }
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true

[dependencies.serde_json]
workspace = true

[target.'cfg(any(windows, unix))'.dependencies]
serialport = "4.7"

[target.'cfg(windows)'.dependencies]
local-encoding-ng = "0.1"
win32job = "2.0"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Security_Cryptography", "Win32_System_Threading"] }

[lints]
workspace = true

