[package]
name = "remoteops-audit"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
regex.workspace = true
remoteops-domain = { path = "../remoteops-domain" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true

