[package]
name = "remoteops-protocol"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
bytes.workspace = true
chrono.workspace = true
hpke.workspace = true
remoteops-domain = { path = "../remoteops-domain" }
rustls.workspace = true
rustls-native-certs.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
x509-parser = "0.18"
zeroize.workspace = true

[dev-dependencies]
rcgen = "0.14"

[lints]
workspace = true
