[package]
name = "remoteops-policy"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
regex.workspace = true
remoteops-domain = { path = "../remoteops-domain" }
remoteops-serial = { path = "../remoteops-serial" }
serde.workspace = true

[lints]
workspace = true

