[package]
name = "remoteops-i18n"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sys-locale = "0.3"
thiserror.workspace = true

[lints]
workspace = true

